from datetime import datetime
from typing import List, Optional

from sqlalchemy import desc
from sqlalchemy.orm import Session

from src.core.structures.structures import DcaStrategyStatus, DcaOrderStatus
from src.persistence.models import DcaStrategy, DcaOrder


class DcaDao:
    """
    Data Access Object for managing Smart DCA Strategies and Orders.
    """

    def __init__(self, session: Session) -> None:
        self.session = session

    def create_strategy(self, strategy: DcaStrategy) -> DcaStrategy:
        """
        Persists a new DCA strategy into the database.
        """
        self.session.add(strategy)
        self.session.commit()
        self.session.refresh(strategy)
        return strategy

    def get_strategy_by_id(self, strategy_identifier: int) -> Optional[DcaStrategy]:
        """
        Retrieves a specific DCA strategy by its primary key.
        """
        return self.session.query(DcaStrategy).filter(DcaStrategy.id == strategy_identifier).first()

    def get_all_strategies(self) -> List[DcaStrategy]:
        """
        Retrieves all DCA strategies ordered by creation date (newest first).
        """
        return self.session.query(DcaStrategy).order_by(desc(DcaStrategy.created_at)).all()

    def bulk_create_orders(self, orders: List[DcaOrder]) -> None:
        """
        Efficiently persists a batch of DCA orders generated by the scheduler.
        """
        self.session.bulk_save_objects(orders)
        self.session.commit()

    def get_due_pending_orders(self, reference_time: datetime) -> List[DcaOrder]:
        """
        Retrieves all pending orders where the planned execution date has passed.
        """
        return self.session.query(DcaOrder).filter(
            DcaOrder.status == DcaOrderStatus.PENDING,
            DcaOrder.planned_date <= reference_time
        ).order_by(DcaOrder.planned_date).all()

    def get_pending_orders_count(self, strategy_identifier: int) -> int:
        """
        Counts the remaining pending orders for a strategy to detect the final execution.
        """
        return self.session.query(DcaOrder).filter(
            DcaOrder.strategy_id == strategy_identifier,
            DcaOrder.status == DcaOrderStatus.PENDING
        ).count()

    def get_orders_for_strategy(self, strategy_identifier: int) -> List[DcaOrder]:
        """
        Retrieves the complete execution calendar for a specific strategy.
        """
        return self.session.query(DcaOrder).filter(
            DcaOrder.strategy_id == strategy_identifier
        ).order_by(DcaOrder.planned_date).all()

    def update_order(self, order: DcaOrder) -> DcaOrder:
        """
        Updates the state of a single DCA order.
        """
        self.session.add(order)
        self.session.commit()
        self.session.refresh(order)
        return order

    def update_strategy_execution_metrics(
            self,
            strategy: DcaStrategy,
            executed_amount_usd: float,
            execution_price: float
    ) -> DcaStrategy:
        """
        Updates the deployed capital and the Average True Price of the strategy atomically.
        Automatically marks the strategy as COMPLETED if the budget is exhausted.
        """
        current_quantity = (strategy.deployed_amount / strategy.average_purchase_price) if strategy.average_purchase_price > 0 else 0.0
        new_quantity = executed_amount_usd / execution_price if execution_price > 0 else 0.0

        strategy.deployed_amount += executed_amount_usd

        total_quantity = current_quantity + new_quantity
        if total_quantity > 0:
            strategy.average_purchase_price = strategy.deployed_amount / total_quantity

        completion_threshold = strategy.total_budget * 0.99
        if strategy.deployed_amount >= completion_threshold:
            strategy.status = DcaStrategyStatus.COMPLETED

        self.session.add(strategy)
        self.session.commit()
        self.session.refresh(strategy)

        return strategy
