sonar.projectName=Poseidon
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.py
sonar.exclusions=backend/alembic/**,frontend/node_modules/**,**/__pycache__/**
