sonar.projectName=Poseidon
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/**/*.spec.ts
sonar.exclusions=backend/alembic/**,frontend/node_modules/**,**/__pycache__/**
