#!/usr/bin/env bash

set -euo pipefail

SQLITE_DATABASE_FILE="/opt/poseidon/alternatives/shadowing/db/poseidon.db"
SQLITE_DATABASE_URL="sqlite://${SQLITE_DATABASE_FILE}"
POSTGRESQL_DATABASE_URL="postgresql://poseidon@media.belier.lan:5432/poseidon"
POSTGRESQL_PASSWORD_FILE="${HOME}/.pgpass"

TIMEZONE="Europe/Paris"

COLOR_RESET='\e[0m'
COLOR_INFORMATION='\e[34m'
COLOR_SUCCESS='\e[32m'
COLOR_ERROR='\e[31m'

print_information_message() {
    echo -e "${COLOR_INFORMATION}[INFORMATION]${COLOR_RESET} $1"
}

print_success_message() {
    echo -e "${COLOR_SUCCESS}[SUCCESS]${COLOR_RESET} $1"
}

print_error_message() {
    echo -e "${COLOR_ERROR}[ERROR]${COLOR_RESET} $1" >&2
}

install_system_package() {
    local package_name="$1"
    print_information_message "Installing missing system package: ${package_name}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update --quiet --yes
    apt-get install --quiet --yes "${package_name}"
}

verify_and_install_dependencies() {
    if [[ ! -f "$SQLITE_DATABASE_FILE" ]]; then
        print_error_message "SQLite database file not found at: $SQLITE_DATABASE_FILE"
        exit 1
    fi
    if ! command -v pgloader &> /dev/null; then
        install_system_package "pgloader"
    fi
    if ! command -v psql &> /dev/null; then
        install_system_package "postgresql-client"
    fi
}

configure_postgresql_authentication() {
    local file_permissions
    local database_password
    if [[ ! -f "${POSTGRESQL_PASSWORD_FILE}" ]]; then
        print_information_message "PostgreSQL password file missing. Interactive configuration required."
        read -s -r -p "Enter PostgreSQL password for poseidon@media.belier.lan: " database_password
        echo ""
        echo "media.belier.lan:5432:poseidon:poseidon:${database_password}" > "${POSTGRESQL_PASSWORD_FILE}"
        chmod 600 "${POSTGRESQL_PASSWORD_FILE}"
        print_success_message "PostgreSQL password file created with secure permissions."
    else
        file_permissions=$(stat -c "%a" "${POSTGRESQL_PASSWORD_FILE}")
        if [[ "${file_permissions}" != "600" ]]; then
            print_information_message "Correcting PostgreSQL password file permissions to 600."
            chmod 600 "${POSTGRESQL_PASSWORD_FILE}"
        fi
    fi
}

execute_migration_process() {
    print_information_message "Starting SQLite to PostgreSQL migration process..."
    verify_and_install_dependencies
    configure_postgresql_authentication
    if pgloader "${SQLITE_DATABASE_URL}" "${POSTGRESQL_DATABASE_URL}"; then
        print_success_message "Data migration via pgloader completed successfully."
    else
        print_error_message "pgloader encountered an execution error."
        exit 1
    fi
    if psql "${POSTGRESQL_DATABASE_URL}" --quiet -v ON_ERROR_STOP=1 -v TARGET_TZ="${TIMEZONE}" <<'END_OF_SQL_SCRIPT'
SET custom.migration_timezone = :'TARGET_TZ';
DO $$
DECLARE
    table_constraint_record RECORD;
    maximum_identifier_value BIGINT;
    timestamp_column_record RECORD;
BEGIN
    FOR table_constraint_record IN
        SELECT column_record.table_name, column_record.column_name
        FROM information_schema.table_constraints AS table_constraint
        JOIN information_schema.key_column_usage AS key_column_usage_record
          ON table_constraint.constraint_name = key_column_usage_record.constraint_name
         AND table_constraint.table_schema = key_column_usage_record.table_schema
        JOIN information_schema.columns AS column_record
          ON column_record.table_schema = table_constraint.table_schema
         AND column_record.table_name = table_constraint.table_name
         AND column_record.column_name = key_column_usage_record.column_name
        WHERE table_constraint.constraint_type = 'PRIMARY KEY'
          AND column_record.data_type IN ('integer', 'bigint')
          AND column_record.is_identity = 'NO'
          AND column_record.column_default IS NULL
          AND column_record.table_schema = 'public'
    LOOP
        RAISE NOTICE 'Configuring identity constraint for "%" ("%")...', table_constraint_record.table_name, table_constraint_record.column_name;
        EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY;', table_constraint_record.table_name, table_constraint_record.column_name);
        EXECUTE format('SELECT coalesce(max(%I), 1) FROM %I;', table_constraint_record.column_name, table_constraint_record.table_name) INTO maximum_identifier_value;
        EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), %s);', table_constraint_record.table_name, table_constraint_record.column_name, maximum_identifier_value);
    END LOOP;
    FOR timestamp_column_record IN
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND data_type LIKE 'timestamp%'
    LOOP
        RAISE NOTICE 'Applying local timezone correction for "%"."%"...', timestamp_column_record.table_name, timestamp_column_record.column_name;
        EXECUTE format('UPDATE %I SET %I = (%I::timestamp AT TIME ZONE %L);', timestamp_column_record.table_name, timestamp_column_record.column_name, timestamp_column_record.column_name, current_setting('custom.migration_timezone'));
    END LOOP;
END;
$$;
ALTER DATABASE poseidon SET timezone TO 'Europe/Paris';
VACUUM FULL;
END_OF_SQL_SCRIPT
    then
        print_success_message "Database sequences synchronized, timestamps corrected, and storage vacuumed."
    else
        print_error_message "PostgreSQL script execution failed."
        exit 1
    fi
    print_success_message "Migration process fully completed."
}

execute_migration_process