from __future__ import annotations

UNALLOCATED_WEALTH_MOVEMENT_EPSILON_USD: float = 0.01
INTEREST_ACCRUAL_COALESCE_MAX_GAP_SECONDS: int = 36 * 60 * 60
ORACLE_PRICE_GAP_DOMINANT_ASSET_SHARE_THRESHOLD: float = 0.70
