ROUTESCAN_AVALANCHE_EVM_CHAIN_ID: int = 43114
ROUTESCAN_AVALANCHE_ETHERSCAN_API_URL: str = f"https://api.routescan.io/v2/network/mainnet/evm/{ROUTESCAN_AVALANCHE_EVM_CHAIN_ID}/etherscan/api"
ROUTESCAN_PAGE_SIZE: int = 10_000
ROUTESCAN_PAGE_DELAY_SECONDS: float = 0.3
ROUTESCAN_HTTP_TIMEOUT_SECONDS: float = 30.0
